version: "3.7"
services:

  odoo18_app:
    image: odoo:18.0
    user: root

    volumes:
      - odoo_data:/var/lib/odoo
      - odoo_custom_addons:/mnt/extra-addons

    networks:
      - postonet

    environment:
      - HOST=odoo_db
      - USER=odoo
      - PASSWORD=e6e29095e50e91c0565853f9c0dc6ad9
      - WORKERS=5
      - PATH=/opt/venv/bin:$PATH

    command: >
      bash -c "
      apt-get update && \
      apt-get install -y --no-install-recommends libxml2-dev libxslt1-dev zlib1g-dev python3-venv && \
      python3 -m venv /opt/venv && \
      /opt/venv/bin/pip install --no-cache-dir erpbrasil.base email-validator num2words phonenumbers brazilcep psycopg2-binary && \
      apt-get clean && rm -rf /var/lib/apt/lists/* && \
      chown -R odoo:odoo /opt/venv && \
      /entrypoint.sh odoo"

    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.odoo.rule=Host(`posto.tectonny.com.br`)
        - traefik.http.routers.odoo.entrypoints=websecure
        - traefik.http.routers.odoo.tls=true
        - traefik.http.routers.odoo.tls.certresolver=letsencryptresolver
        - traefik.http.services.odoo.loadbalancer.server.port=8069

  odoo_db:
    image: postgres:15

    volumes:
      - odoo_db_data:/var/lib/postgresql/data/pgdata

    networks:
      - postonet
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=e6e29095e50e91c0565853f9c0dc6ad9
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata

    deploy:
      placement:
        constraints:
          - node.role == manager

volumes:
  odoo_data:
  odoo_custom_addons:
  odoo_db_data:

networks:
  postonet:
    external: true
    attachable: true
    name: postonet
